FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY src /app/src

ENV PYTHONPATH=/app/src

EXPOSE 8501

CMD ["streamlit", "run", "src/dst_airlines/streamlit_app/flight_analyzer.py", "--server.address=0.0.0.0", "--server.port=8501"]