name: "Ingest Source Data"
description: "Extract flight data from Aviationstack and ingest into MongoDB"

inputs:
  script-path:
    description: "Path to the ingestion script"
    required: false
    default: "etl/extract/aviationstack.py"

runs:
  using: "composite"
  steps:
    - name: Run ingestion script
      run: python "${{ inputs.script-path }}"
      shell: bash